Traceback (most recent call last):
  File "/app/client.py", line 18, in <module>
    main()
  File "/app/client.py", line 11, in main
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Sending: Hello, Server!
Traceback (most recent call last):
  File "/app/client.py", line 18, in <module>
    main()
  File "/app/client.py", line 14, in main
    data = s.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
Sending: Hello, Server!
Received: Hello, Server!
